spring:
  application:
    name: weibo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weibo?characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: yorkroot
  cloud:
    sentinel:
      enabled: true
      transport:
        dashboard: 127.0.0.1:8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
server:
  port: 8006