server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    loadbalancer:
      ribbon:
        enabled: false





logging:
  level:
    org.springframework.cloud.gateway: debug
